export const produtosMockados = [
  {
    nome: "Pizza Margherita",
    descricao: "Massa fina, molho de tomate, queijo e manjericão.",
    preco: 30.5,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Hambúrguer",
    descricao: "Pão artesanal, carne bovina, queijo, bacon e alface.",
    preco: 25.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Sushi Combo",
    descricao: "10 peças de sushi variado.",
    preco: 40.0,
    imagemPrato: "",
    alergenicos: "Soja, Peixe",
  },
  {
    nome: "Pizza Margherita",
    descricao: "Massa fina, molho de tomate, queijo e manjericão.",
    preco: 30.5,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Hambúrguer",
    descricao: "Pão artesanal, carne bovina, queijo, bacon e alface.",
    preco: 25.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Sushi Combo",
    descricao: "10 peças de sushi variado.",
    preco: 40.0,
    imagemPrato: "",
    alergenicos: "Soja, Peixe",
  },
  {
    nome: "Espaguete Carbonara",
    descricao: "Espaguete ao molho carbonara, com bacon e parmesão.",
    preco: 35.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Pizza Margherita",
    descricao: "Massa fina, molho de tomate, queijo e manjericão.",
    preco: 30.5,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Hambúrguer",
    descricao: "Pão artesanal, carne bovina, queijo, bacon e alface.",
    preco: 25.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Sushi Combo",
    descricao: "10 peças de sushi variado.",
    preco: 40.0,
    imagemPrato: "",
    alergenicos: "Soja, Peixe",
  },
  {
    nome: "Pizza Margherita",
    descricao: "Massa fina, molho de tomate, queijo e manjericão.",
    preco: 30.5,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Hambúrguer",
    descricao: "Pão artesanal, carne bovina, queijo, bacon e alface.",
    preco: 25.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
  {
    nome: "Sushi Combo",
    descricao: "10 peças de sushi variado.",
    preco: 40.0,
    imagemPrato: "",
    alergenicos: "Soja, Peixe",
  },
  {
    nome: "Espaguete Carbonara",
    descricao: "Espaguete ao molho carbonara, com bacon e parmesão.",
    preco: 35.0,
    imagemPrato: "",
    alergenicos: "Glúten, Lactose",
  },
];

export const adicionaisMockados = [
  {
    nome: "Batata Frita",
    descricao: "Porção de batata frita crocante.",
    preco: 10.0,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Molho Especial",
    descricao: "Molho da casa com ingredientes secretos.",
    preco: 5.0,
    imagemPrato: "",
    alergenicos: "Glúten",
  },
  {
    nome: "Queijo Extra",
    descricao: "Adicional de queijo para o seu prato.",
    preco: 3.0,
    imagemPrato: "",
    alergenicos: "Lactose",
  },
  {
    nome: "Bacon Extra",
    descricao: "Adicional de bacon crocante.",
    preco: 4.5,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Batata Frita",
    descricao: "Porção de batata frita crocante.",
    preco: 10.0,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Molho Especial",
    descricao: "Molho da casa com ingredientes secretos.",
    preco: 5.0,
    imagemPrato: "",
    alergenicos: "Glúten",
  },
  {
    nome: "Queijo Extra",
    descricao: "Adicional de queijo para o seu prato.",
    preco: 3.0,
    imagemPrato: "",
    alergenicos: "Lactose",
  },
  {
    nome: "Bacon Extra",
    descricao: "Adicional de bacon crocante.",
    preco: 4.5,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Batata Frita",
    descricao: "Porção de batata frita crocante.",
    preco: 10.0,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Molho Especial",
    descricao: "Molho da casa com ingredientes secretos.",
    preco: 5.0,
    imagemPrato: "",
    alergenicos: "Glúten",
  },
  {
    nome: "Queijo Extra",
    descricao: "Adicional de queijo para o seu prato.",
    preco: 3.0,
    imagemPrato: "",
    alergenicos: "Lactose",
  },
  {
    nome: "Bacon Extra",
    descricao: "Adicional de bacon crocante.",
    preco: 4.5,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Batata Frita",
    descricao: "Porção de batata frita crocante.",
    preco: 10.0,
    imagemPrato: "",
    alergenicos: "",
  },
  {
    nome: "Molho Especial",
    descricao: "Molho da casa com ingredientes secretos.",
    preco: 5.0,
    imagemPrato: "",
    alergenicos: "Glúten",
  },
  {
    nome: "Queijo Extra",
    descricao: "Adicional de queijo para o seu prato.",
    preco: 3.0,
    imagemPrato: "",
    alergenicos: "Lactose",
  },
  {
    nome: "Bacon Extra",
    descricao: "Adicional de bacon crocante.",
    preco: 4.5,
    imagemPrato: "",
    alergenicos: "",
  },
];
